#! /bin/sh
if type pacman > /dev/null 2>&1; then
    sudo pacman -S archlinux-keyring && sudo pacman -Syu
    if type yay > /dev/null 2>&1; then
        yay -Syu --aur
    fi
elif type apt-get > /dev/null 2>&1; then
    sudo apt-get update && sudo apt-get full-upgrade
fi

