#! /bin/sh
if type pacman > /dev/null; then
    sudo pacman -Syu
    if type yay > /dev/null; then
        yay -Syu --aur
    fi
elif type apt-get > /dev/null; then
    sudo apt-get update && sudo apt-get full-upgrade
fi

