#! /bin/sh
if type yaourt > /dev/null; then
    yaourt -Syu --aur
elif type pacman > /dev/null; then
    sudo pacman -Syu
elif type apt-get > /dev/null; then
    sudo apt-get update && sudo apt-get full-upgrade
fi

